# What is a Tensor

## Tensor is a matrix or vector that lives in a structure, connected to other elements of the same structure

## If one changes an element of the structure then other elements change as well

<img src="ExampleNetwork.png" width=1200 height=1200 />

## As per definition by Dan Fliesch

#### Youtube video - Tensor explanation by Dan Fliesch :- https://www.youtube.com/watch?v=f5liqUk0ZTw

### Tensors are a combination of Components and Basis vectors. This combination makes them so powerful

### All observers in all reference frames, agree, not on the basis vectors nor on the components, but on the combination of components and basis vectors

### The reason is basis vectors transform one way between reference frames, and the components transform in just such a way so as to keep the combination of components and basis vectors the same for all observers

### It was this characteristics of the Tensors that caused Lilian Lieber to call tensors "The facts of the universe"

#### Link to Lilian Leiber Book  "The Einstein Theory of relativity" where she explains Tensors in detail at page 127 (navigate to 140 in the page navigator)
https://fdocuments.in/document/the-einstein-theory-of-relativity-lillian-r-lieber-19661945pdf.html

In [8]:
import numpy as np

### Initial Layer 1 activations

In [7]:
L1 = np.array([4.5,8,2.4])
L1 = L1.reshape(3,1)
L1

array([[4.5],
       [8. ],
       [2.4]])

### Initial Weight matrix

In [22]:
W12 = np.array([[-2,0.8,3.0],
               [1.6,1,1.5],
               [0.4,-0.6,2]]).reshape(3,3)
W12

array([[-2. ,  0.8,  3. ],
       [ 1.6,  1. ,  1.5],
       [ 0.4, -0.6,  2. ]])

### Initial Layer 2 activations

In [23]:
L2 = W12.dot(L1)
L2

array([[ 4.6],
       [18.8],
       [ 1.8]])

### Suppose we Change L1 activations with the help of below transformation

In [24]:
A= np.array([[2,0,0],
               [0,1,0],
               [0,0,0.2]]).reshape(3,3)

### This changes L1 activations as follows

In [25]:
L1hat = A.dot(L1)
L1hat

array([[9.  ],
       [8.  ],
       [0.48]])

### And corresponding L2 if W12 does not adjust itself and does not behave like a Tensor

In [30]:
L2 = W12.dot(L1hat)
L2

array([[-10.16],
       [ 23.12],
       [ -0.24]])

### To prevent retraining the network, the weight matrix behaves like a Tensor such that it adjusts itself such that the activations of L2 do not change

### It uses the inverse of A to adjust itself

In [31]:
#Calculate A inverse
Ainv = np.linalg.inv(A)

### Adjusted W12

In [32]:
W12hat = W12.dot(Ainv)
W12hat

array([[-1. ,  0.8, 15. ],
       [ 0.8,  1. ,  7.5],
       [ 0.2, -0.6, 10. ]])

### The result is that L2 remains unchanged and hence the network need not be retrained

In [33]:
L2 = W12hat.dot(L1hat)
L2

array([[ 4.6],
       [18.8],
       [ 1.8]])